"""Initial migration

Revision ID: 28a1d17dcdd6
Revises: 
Create Date: 2026-01-22 12:37:27.692974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a1d17dcdd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_categories_id'), 'heritage_categories', ['id'], unique=False)
    op.create_index(op.f('ix_heritage_categories_name'), 'heritage_categories', ['name'], unique=True)
    op.create_table('heritage_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_zh', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('history_zh', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('designation_level', sa.String(length=100), nullable=True),
    sa.Column('designation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['heritage_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_sites_city'), 'heritage_sites', ['city'], unique=False)
    op.create_index(op.f('ix_heritage_sites_id'), 'heritage_sites', ['id'], unique=False)
    op.create_index(op.f('ix_heritage_sites_name'), 'heritage_sites', ['name'], unique=False)
    op.create_index(op.f('ix_heritage_sites_name_zh'), 'heritage_sites', ['name_zh'], unique=False)
    op.create_index(op.f('ix_heritage_sites_slug'), 'heritage_sites', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_sites_slug'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_name_zh'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_name'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_id'), table_name='heritage_sites')
    op.drop_index(op.f('ix_heritage_sites_city'), table_name='heritage_sites')
    op.drop_table('heritage_sites')
    op.drop_index(op.f('ix_heritage_categories_name'), table_name='heritage_categories')
    op.drop_index(op.f('ix_heritage_categories_id'), table_name='heritage_categories')
    op.drop_table('heritage_categories')
    # ### end Alembic commands ###
