"""add images field to news

Revision ID: 2a1a90ef3813
Revises: 7bb3ca923400
Create Date: 2026-01-26 12:11:16.469994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1a90ef3813'
down_revision: Union[str, None] = '7bb3ca923400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'images')
    # ### end Alembic commands ###
